/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hzy_cnn_CustomView_RSA_RSAUtils */

#ifndef _Included_com_hzy_cnn_CustomView_RSA_RSAUtils
#define _Included_com_hzy_cnn_CustomView_RSA_RSAUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hzy_cnn_CustomView_RSA_RSAUtils
 * Method:    rsaLock
 * Signature: ()V
 */
JNIEXPORT jstring
JNICALL Java_com_hzy_rsa_RSA_RSAUtils_rsaLock
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
