/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdlib.h>
#include <android/log.h>
/* Header for class com_hzy_cnn_CustomView_RSA_RSAUtils */

#ifndef _Included_com_hzy_cnn_CustomView_RSA_RSAUtils
#define _Included_com_hzy_cnn_CustomView_RSA_RSAUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hzy_cnn_CustomView_RSA_RSAUtils
 * Method:    rsaLock
 * Signature: ()V
 */
JNIEXPORT jstring
JNICALL Java_com_hzy_rsa_RSA_RSAUtils_rsaLock
        (JNIEnv *, jclass);


#define LOG_TAG "RSAUtils"
#define LOGD(...)  __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__) // 定义LOGD类型
#define LOGI(...)  __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)  // 定义LOGI类型
#define LOGW(...)  __android_log_print(ANDROID_LOG_WARN, LOG_TAG, __VA_ARGS__)  // 定义LOGW类型
#define LOGE(...)  __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__) // 定义LOGE类型
#define LOGF(...)  __android_log_print(ANDROID_LOG_FATAL, LOG_TAG, __VA_ARGS__) // 定义LOGF类

#ifdef __cplusplus
}
#endif
#endif
